@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.accessToken}}
@questionId = 55e94ccd-8d13-4877-a28b-6d597a56d3e5
# Substituir pelo id da pergunta que deseja editar/deletar/responder

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Caio",
  "email": "caio@gmail.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "caio@gmail.com",
  "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta",
  "content": "Conteúdo da pergunta"
}

###

# @name edit_question
PUT {{baseUrl}}/questions/{{questionId}} 
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Novo título",
  "content": "Novo conteúdo"
}

###

# @name delete_question
DELETE  {{baseUrl}}/questions/{{questionId}} 
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name answer_question
DELETE  {{baseUrl}}/questions/{{questionId}}/answers
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "Conteúdo da resposta"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}