@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.accessToken}}
@questionId = f0318815-0e05-4891-a585-447121ddba2f
# Substituir pelo id da pergunta que deseja editar/deletar/responder
@answerId = 381ef55c-c3f8-4b9f-9cf8-66819af3c3bb
# Substituir pelo id da resposta que deseja editar/deletar

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Caio",
  "email": "caio@gmail.com",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "caio@gmail.com",
  "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova pergunta",
  "content": "Conteúdo da pergunta"
}

###

# @name edit_question
PUT {{baseUrl}}/questions/{{questionId}} 
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Novo título",
  "content": "Novo conteúdo"
}

###

# @name delete_question
DELETE  {{baseUrl}}/questions/{{questionId}} 
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name answer_question
POST  {{baseUrl}}/questions/{{questionId}}/answers
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "Conteúdo da resposta"
}

###

# @name edit_answer
PUT {{baseUrl}}/answer/{{answerId}} 
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "Novo conteúdo"
}

###

# @name delete_answer
DELETE  {{baseUrl}}/answers/{{answerId}} 
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}